# Solving Linear Systems

::: {.callout-note}

# Existence and Uniqueness Question


The two fundamental questions about a linear system are:

1. Is the system consistent; that is, does at least one solution exist?
2. If a solution exists, is it the only one; that is, is the solution unique

<br>

**Examples from [Linear Systems (page 1)](/p1.html)** 

A consistent system that has a unique solution

$$
\left[\begin{array}{cc|c}
1 & -2 & -1 \\
-1 & 3 & 3
\end{array}\right]
$$

A consistent system that has infinitely many solutions

$$
\left[\begin{array}{cc|c}
1 & -2 & -1 \\
-1 & 2 & 1
\end{array}\right]  
$$

An inconsistent system (A system that has no solution)

$$
\left[\begin{array}{cc|c}
1 & -2 & -1 \\
-1 & 2 & 3
\end{array}\right]
$$


:::


## The workflow for solving a linear system {.unnumbered}

1.  The linear system is written out in a system of equations.
2.  Convert the system of equations to an augmented matrix.
3.  Use elementary row operations to reduce the matrix to row echelon form.
4.  Convert the reduced row echelon form back to a system of equations.


### Infinitely Many Solutions Example {.unnumbered}

::: panel-tabset

# Step 1

1.  The linear system is written out in a system of equations.

Here is a linear system written as a system of equations.

$$
\begin{cases}
&\;\;x_1 &- &3x_2 &+ &4x_3 &= -4 \\
&3x_1 &- &7x_2 &+ &7x_3 &= -8 \\
&2x_1 &- &6x_2 &- &8x_3 &= -8
\end{cases}
$$

# Step 2

2.  Convert the system of equations to an augmented matrix.

The system of equations is converted to an augmented matrix.

$$
\begin{cases}
&\;\;x_1 &- &3x_2 &+ &4x_3 &= -4 \\
&3x_1 &- &7x_2 &+ &7x_3 &= -8 \\
&2x_1 &- &6x_2 &- &8x_3 &= -8
\end{cases}
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccc|c}
1 & -3 & 4 & -4 \\
3 & -7 & 7 & -8 \\
2 & -6 & -8 & -8
\end{array}\right]
$$

# Step 3

3.  Use elementary row operations to reduce the matrix to row echelon form.

$$
\left[\begin{array}{ccc|c}
1 & -3 & 4 & -4 \\
3 & -7 & 7 & -8 \\
2 & -6 & -8 & -8
\end{array}\right]
$$

$$
\downarrow
$$

```{python}
import sympy as sp
from sympy import init_printing
init_printing()

A = sp.Matrix([
    [1, -3, 4, -4],
    [3, -7, 7, -8],
    [2, -6, 8, -8]
])

A.echelon_form()
```

# Step 4

4.  Convert the reduced row echelon form back to a system of equations.

$$
\displaystyle \left[\begin{matrix}1 & -3 & 4 & -4\\0 & 2 & -5 & 4\\0 & 0 & 0 & 0\end{matrix}\right]
$$

$$
\downarrow
$$

$$
\begin{cases}
x_1 &- &3x_2 &+ &4x_3 &= -4 \\
& &\;\;2x_2 &- &5x_3 &= \;\;\;4 \\
& & & &0x_3 &= \;\;\;0
\end{cases}
$$

# Finish

The system of equations is written out as so:

$$
\begin{cases}
x_1 &- &3x_2 &+ &4x_3 &= -4 \\
& &\;\;2x_2 &- &5x_3 &= \;\;\;4 \\
& & & &0x_3 &= \;\;\;0
\end{cases}
$$

We can see that the system is consistent because the last equation is $0x_3 = 0$ which is always true. Therefore, the system has infinitely many solutions.

:::

### No Solution Example {.unnumbered}

::: panel-tabset

# Step 1

1.  The linear system is written out in a system of equations.

Here is a linear system written as a system of equations.

$$
\begin{cases}
& & &\;\;x_2 &+ &4x_3 &= -5 \\
&\;\;x_1 &- &3x_2 &+ &5x_3 &= -2 \\
&3x_1 &+ &7x_2 &+ &7x_3 &= \;\;\;6
\end{cases}
$$

# Step 2

2.  Convert the system of equations to an augmented matrix.

The system of equations is converted to an augmented matrix.

$$
\begin{cases}
& & &\;\;x_2 &+ &4x_3 &= -5 \\
&\;\;x_1 &- &3x_2 &+ &5x_3 &= -2 \\
&3x_1 &+ &7x_2 &+ &7x_3 &= \;\;\;6
\end{cases}
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccc|c}
0 & 1 & 4 & -5 \\
1 & 3 & 5 & -2 \\
3 & 7 & 7 & 6
\end{array}\right]
$$

# Step 3

3.  Use elementary row operations to reduce the matrix to row echelon form.


$$
\left[\begin{array}{ccc|c}
0 & 1 & 4 & -5 \\
1 & 3 & 5 & -2 \\
3 & 7 & 7 & 6
\end{array}\right]
$$

$$
\downarrow
$$

```{python}
import sympy as sp  
from sympy import init_printing
init_printing()

A = sp.Matrix([
    [0, 1, 4, -5],
    [1, 3, 5, -2],
    [3, 7, 7, 6]
])

A.echelon_form()
```

# Step 4

4.  Convert the reduced row echelon form back to a system of equations.

$$
\displaystyle \left[\begin{matrix}1 & 3 & 5 & -2\\0 & 1 & 4 & -5\\0 & 0 & 0 & 2\end{matrix}\right]
$$

$$  
\downarrow
$$

$$
\begin{cases}
x_1 &+ &3x_2 &+ &5x_3 &= -2 \\
& &\;\;x_2 &+ &4x_3 &= -5 \\
& & & &0x_3 &= \;\;\;2
\end{cases}
$$

# Finish

The system of equations is written out as so:

$$
\begin{cases}
x_1 &+ &3x_2 &+ &5x_3 &= -2 \\
& &\;\;x_2 &+ &4x_3 &= -5 \\
& & & &0x_3 &= \;\;\;2
\end{cases}
$$

We can see that the system is inconsistent because the last equation is $0x_3 = 2$ which is impossible. No value of $x_3$ will make this equation true. Therefore, the system has no solution.

:::